/*
 * LibreClinica is distributed under the
 * GNU Lesser General Public License (GNU LGPL).
 *
 * For details see: https://libreclinica.org/license
 * copyright (C) 2026 Department of Ophthalmology and Optometry,
 *                     Medical University of Vienna
 */
package org.akaza.openclinica.odm.characterisation;

import static org.akaza.openclinica.odm.characterisation.GoldenAssertions.assertUnmarshalled;
import static org.junit.Assert.assertNull;

import java.io.ByteArrayInputStream;
import java.nio.charset.StandardCharsets;

import org.akaza.openclinica.domain.rule.RulesPostImportContainer;
import org.akaza.openclinica.service.xml.OdmJaxbContext;
import org.junit.Test;

/**
 * Phase B.0 characterisation for the rules-XML <em>unmarshaller</em> code
 * path driven by {@code ImportRuleServlet}. Pins the contract that Castor
 * can deserialise an institutional rule-set XML file into a non-null
 * {@link RulesPostImportContainer} with the expected post-parse structure.
 *
 * <p>Uses {@code properties/mapping.xml} (the generic Castor mapping used by
 * ImportRuleServlet, distinct from {@code mappingMarshaller.xml} used by
 * downloads and {@code mappingMarshallerMetadata.xml} used by the metadata
 * extract).
 *
 * <p>Why not a "compare against golden bean snapshot": there is no canonical
 * Java-side bean snapshot format that survives a Castor → JAXB swap, because
 * the swap may change which collection implementation each field uses
 * ({@code java.util.ArrayList} vs. {@code java.util.LinkedList}, etc.). The
 * test instead asserts the post-parse <em>contract</em> the production code
 * relies on: the container is non-null and {@link RulesPostImportContainer#getRuleDefs()}
 * + {@link RulesPostImportContainer#getRuleSets()} both return non-null
 * containers (even when empty) so the production iteration paths never
 * surprise-NPE on a JAXB-swapped implementation.
 *
 * <p>When Phase B.3 swaps Castor → JAXB, this test runs unchanged against
 * the JAXB unmarshaller (with the corresponding mapping mechanism, likely
 * generated by xjc). If the JAXB-parsed container fails any of these
 * assertions, the production rule-import paths regress and amendment to
 * DR-006 is in scope.
 */
public class CastorRulesUnmarshallerCharacterisationTest {

    /**
     * Pin the smallest deserialisable input: an empty {@code <Rules>} root.
     * Castor must parse this without error and yield a non-null container.
     *
     * <p><strong>Pinned current behaviour:</strong> Castor leaves the
     * {@code ruleDefs} / {@code ruleSets} collection fields <em>null</em>
     * after parsing an empty document, rather than initialising them to
     * empty lists. The production callers (e.g. {@code ImportRuleServlet})
     * therefore must null-check before iterating. A Phase B.3 JAXB binding
     * that emits empty lists instead of null is <em>more</em> defensive
     * than today's contract; this test updates rather than breaks if JAXB
     * picks that path. The reverse - flipping current null behaviour to
     * something the production code does not handle - is what this assert
     * guards against.
     *
     * <p>Hand-written input rather than captured from the marshaller,
     * because the marshaller and unmarshaller mapping files differ — using
     * the marshaller's output as the unmarshaller's input would test the
     * wrong thing.
     */
    @Test
    public void emptyRulesRootUnmarshalsToNonNullContainer() throws Exception {
        String inputXml =
                "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                + "<Rules xmlns=\"http://www.openclinica.org/ns/rules/v3.1\"/>\n";

        RulesPostImportContainer parsed = unmarshalViaJaxb(inputXml);

        assertUnmarshalled(parsed);
        // Phase B.3 PR 1/3: JAXB with @XmlAccessorType(NONE) + only a root
        // annotation leaves the unbound collection fields null after parsing
        // an empty document — same contract Castor 1.4.1 provided. Production
        // callers (e.g. ImportRuleServlet) null-check before iterating.
        // PR 2/3 may add @XmlElement on these collections; if it does, the
        // post-parse state flips to empty-list and these asserts will be
        // updated to assertTrue(list.isEmpty()) in that PR.
        assertNull("Pinned 2026-05-28 (Castor) and re-pinned in B.3 PR 1/3 (JAXB):"
                + " getRuleDefs() returns null after parsing an empty <Rules>"
                + " envelope. PR 2/3 may flip this to empty-list.",
                parsed.getRuleDefs());
        assertNull("Same as above for getRuleSets().",
                parsed.getRuleSets());
    }

    /**
     * Production code path equivalent to {@code ImportRuleServlet.handleLoadCastor(File)}
     * after Phase B.3 PR 1/3 swapped Castor → {@code javax.xml.bind} 2.3.x
     * JAXB via {@link OdmJaxbContext}. The {@code File} → {@code ByteArrayInputStream}
     * substitution is the only adaptation.
     */
    private static RulesPostImportContainer unmarshalViaJaxb(String inputXml) {
        OdmJaxbContext ctx = new OdmJaxbContext();
        return ctx.unmarshalRulesImport(
                new ByteArrayInputStream(inputXml.getBytes(StandardCharsets.UTF_8)));
    }
}
