/*
 * LibreClinica is distributed under the
 * GNU Lesser General Public License (GNU LGPL).
 *
 * For details see: https://libreclinica.org/license
 * copyright (C) 2026 Department of Ophthalmology and Optometry,
 *                     Medical University of Vienna
 */
package org.akaza.openclinica.odm.characterisation;

import static org.akaza.openclinica.odm.characterisation.GoldenAssertions.assertUnmarshalled;
import static org.junit.Assert.assertNull;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.io.StringReader;
import java.nio.charset.StandardCharsets;

import org.akaza.openclinica.domain.rule.RulesPostImportContainer;
import org.exolab.castor.mapping.Mapping;
import org.exolab.castor.xml.Unmarshaller;
import org.exolab.castor.xml.XMLContext;
import org.junit.Test;
import org.xml.sax.InputSource;

/**
 * Phase B.0 characterisation for the rules-XML <em>unmarshaller</em> code
 * path driven by {@code ImportRuleServlet}. Pins the contract that Castor
 * can deserialise an institutional rule-set XML file into a non-null
 * {@link RulesPostImportContainer} with the expected post-parse structure.
 *
 * <p>Uses {@code properties/mapping.xml} (the generic Castor mapping used by
 * ImportRuleServlet, distinct from {@code mappingMarshaller.xml} used by
 * downloads and {@code mappingMarshallerMetadata.xml} used by the metadata
 * extract).
 *
 * <p>Why not a "compare against golden bean snapshot": there is no canonical
 * Java-side bean snapshot format that survives a Castor → JAXB swap, because
 * the swap may change which collection implementation each field uses
 * ({@code java.util.ArrayList} vs. {@code java.util.LinkedList}, etc.). The
 * test instead asserts the post-parse <em>contract</em> the production code
 * relies on: the container is non-null and {@link RulesPostImportContainer#getRuleDefs()}
 * + {@link RulesPostImportContainer#getRuleSets()} both return non-null
 * containers (even when empty) so the production iteration paths never
 * surprise-NPE on a JAXB-swapped implementation.
 *
 * <p>When Phase B.3 swaps Castor → JAXB, this test runs unchanged against
 * the JAXB unmarshaller (with the corresponding mapping mechanism, likely
 * generated by xjc). If the JAXB-parsed container fails any of these
 * assertions, the production rule-import paths regress and amendment to
 * DR-006 is in scope.
 */
public class CastorRulesUnmarshallerCharacterisationTest {

    /**
     * Pin the smallest deserialisable input: an empty {@code <Rules>} root.
     * Castor must parse this without error and yield a non-null container.
     *
     * <p><strong>Pinned current behaviour:</strong> Castor leaves the
     * {@code ruleDefs} / {@code ruleSets} collection fields <em>null</em>
     * after parsing an empty document, rather than initialising them to
     * empty lists. The production callers (e.g. {@code ImportRuleServlet})
     * therefore must null-check before iterating. A Phase B.3 JAXB binding
     * that emits empty lists instead of null is <em>more</em> defensive
     * than today's contract; this test updates rather than breaks if JAXB
     * picks that path. The reverse - flipping current null behaviour to
     * something the production code does not handle - is what this assert
     * guards against.
     *
     * <p>Hand-written input rather than captured from the marshaller,
     * because the marshaller and unmarshaller mapping files differ — using
     * the marshaller's output as the unmarshaller's input would test the
     * wrong thing.
     */
    @Test
    public void emptyRulesRootUnmarshalsToNonNullContainer() throws Exception {
        String inputXml =
                "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                + "<Rules xmlns=\"http://www.openclinica.org/ns/rules/v3.1\"/>\n";

        RulesPostImportContainer parsed = unmarshalViaCastor(inputXml);

        assertUnmarshalled(parsed);
        assertNull("Castor 1.4.1 leaves getRuleDefs() null after parsing an"
                + " empty <Rules> envelope (pinned 2026-05-28); production"
                + " null-checks before iterating. If JAXB returns an empty"
                + " list here, that is a strict improvement and this assert"
                + " should be updated to assertTrue(list.isEmpty()).",
                parsed.getRuleDefs());
        assertNull("Castor 1.4.1 leaves getRuleSets() null after parsing an"
                + " empty <Rules> envelope (pinned 2026-05-28); same note.",
                parsed.getRuleSets());
    }

    /**
     * Production code path lifted from
     * {@code ImportRuleServlet.loadCastor(File)}. The {@code FileReader} →
     * {@code StringReader} substitution is the only adaptation.
     */
    private static RulesPostImportContainer unmarshalViaCastor(String inputXml) throws Exception {
        byte[] mappingBytes = readClasspathResource("/properties/mapping.xml");
        Mapping mapping = new Mapping();
        mapping.loadMapping(new InputSource(new ByteArrayInputStream(mappingBytes)));

        XMLContext xmlContext = new XMLContext();
        xmlContext.addMapping(mapping);

        Unmarshaller unmarshaller = xmlContext.createUnmarshaller();
        unmarshaller.setWhitespacePreserve(false);
        unmarshaller.setClass(RulesPostImportContainer.class);

        StringReader reader = new StringReader(inputXml);
        return (RulesPostImportContainer) unmarshaller.unmarshal(reader);
    }

    private static byte[] readClasspathResource(String path) throws Exception {
        try (InputStream in = CastorRulesUnmarshallerCharacterisationTest.class
                .getResourceAsStream(path)) {
            if (in == null) {
                throw new IllegalStateException("Castor mapping missing: " + path);
            }
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            byte[] buf = new byte[8192];
            int n;
            while ((n = in.read(buf)) != -1) {
                out.write(buf, 0, n);
            }
            return out.toByteArray();
        }
    }
}
