"""Browser de-identification (layer 1) contract: the converter still parses a stripped .e2e.

The SPA strips patient identity out of a Heidelberg .e2e in the browser before
upload (web/src/spa/src/lib/deid/e2eDeidentify.ts): in every patient-data
chunk (type 9) first_name / title / birthdate / sex become zero bytes and
surname / patient_id become the study label.

``phi-original.e2e`` / ``phi-stripped.e2e`` are generated by
``web/src/spa/src/lib/__tests__/fixtures/generate_fixtures.py`` (the stripped
one by an implementation independent of the TypeScript one); the vitest spec
``e2eDeidentify.spec.ts`` checks the TypeScript strip reproduces it byte for byte. This
test closes the loop on the Python side: the real reader (oct-converter, which
every sidecar path here goes through) must read the stripped file, see no
identity, and still extract the image.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from muw_e2e_converter.fundus_extract import extract_fundus_png

FIXTURES = (
    Path(__file__).resolve().parents[2]
    / "web" / "src" / "spa" / "src" / "lib" / "__tests__" / "fixtures"
)
ORIGINAL = FIXTURES / "phi-original.e2e"
STRIPPED = FIXTURES / "phi-stripped.e2e"
LABEL = "HAE-042"

pytestmark = pytest.mark.skipif(
    not (ORIGINAL.is_file() and STRIPPED.is_file()),
    reason="SPA de-identification fixtures not present in this checkout",
)


def _patient_chunks(path: Path) -> list[dict]:
    from oct_converter.readers import E2E

    return E2E(str(path)).read_all_metadata()["patient_data"]


def test_original_fixture_really_carries_identity() -> None:
    (p,) = _patient_chunks(ORIGINAL)
    assert p["first_name"] == "Maximilian"
    assert p["surname"] == "Mustermann"
    assert p["title"] == "Dr."
    assert p["patient_id"] == "MRN-778899"
    assert p["birthdate"] == 19700101


def test_stripped_patient_chunk_has_the_contract_values() -> None:
    (p,) = _patient_chunks(STRIPPED)
    assert p["first_name"] == ""
    assert p["title"] == ""
    assert p["surname"] == LABEL
    assert p["patient_id"] == LABEL
    assert p["birthdate"] == 0
    assert p["sex"] == ""


def test_reader_attributes_after_a_volume_read_carry_the_label_only() -> None:
    from oct_converter.readers import E2E

    reader = E2E(str(STRIPPED))
    reader.read_oct_volume()  # no B-scan pixels in the fixture: must not raise
    assert reader.patient_id == LABEL
    assert reader.surname == LABEL
    assert not reader.first_name
    # birthdate 0 is not a date: the reader reports none rather than inventing one
    assert reader.birthdate in (None, "0")


def test_fundus_image_is_extracted_identically_before_and_after() -> None:
    before_png, before_size = extract_fundus_png(ORIGINAL)
    after_png, after_size = extract_fundus_png(STRIPPED)
    assert before_size == after_size == (24, 16)
    assert after_png == before_png  # pixels untouched


def test_the_two_files_differ_only_inside_the_patient_payload() -> None:
    a, b = ORIGINAL.read_bytes(), STRIPPED.read_bytes()
    assert len(a) == len(b)
    changed = [i for i in range(len(a)) if a[i] != b[i]]
    assert changed, "the strip must change something"
    # one patient chunk: 127-byte payload right after its 60-byte header
    start = 36 + 52 + 4 * 44 + 60
    assert all(start <= i < start + 127 for i in changed)
