/**
 * Tests for {@link parseE2e} — the OCT-Upload-Portal's client-side
 * Heidelberg `.e2e` header reader.
 *
 * <p>Fixtures live next to this spec under {@code fixtures/} and are
 * regenerated by {@code fixtures/generate_fixtures.py}:
 *
 * <pre>
 *   single-scan.e2e        ONE volume, PatientId="TEST-001",
 *                          scanDate=2024-01-15T00:00:00Z, OD, 49 B-scans
 *   multi-scan-OD-OS.e2e   TWO volumes, both PatientId="TEST-002",
 *                          both scanDate=2024-03-20T00:00:00Z,
 *                          Volume 0 = OD/49, Volume 1 = OS/49
 * </pre>
 *
 * <p>Run {@code python3 generate_fixtures.py} from the fixtures dir to
 * rebuild them; the Python script documents the byte layout so future
 * maintainers can patch the generator without re-reading {@code oct_converter}.
 *
 * <p>Tests use Node's filesystem to load the fixtures and wrap them in
 * the browser-equivalent {@link File} (jsdom's polyfill ships in vitest's
 * default env) so {@link parseE2e}'s production signature is exercised
 * end-to-end.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { parseE2e, type E2eScan } from '../e2eParser';

/**
 * Loads a fixture relative to the package root (`web/src/spa/`) — using
 * a cwd-relative path because vitest's jsdom environment shadows
 * `import.meta.url` against `window.location`, breaking
 * `new URL('./fixtures/x', import.meta.url)`. Vitest sets the cwd to
 * the package root that owns `vite.config.ts`, so this is stable.
 */
function loadFixture(name: string): File {
  const fixturePath = resolve(
    process.cwd(),
    'src/lib/__tests__/fixtures',
    name,
  );
  const bytes = readFileSync(fixturePath);
  return new File([new Uint8Array(bytes)], name, {
    type: 'application/octet-stream',
  });
}

describe('parseE2e', () => {
  it('parseE2e_singleScan_returnsOneScan', async () => {
    const file = loadFixture('single-scan.e2e');
    const scans = await parseE2e(file);

    expect(scans).toHaveLength(1);
    const scan: E2eScan = scans[0]!;
    expect(scan.patientId).toBe('TEST-001');
    expect(scan.laterality).toBe('OD');
    expect(scan.nBscans).toBe(49);
    expect(scan.scanIndex).toBe(0);
    expect(scan.scanDate.toISOString().slice(0, 10)).toBe('2024-01-15');
  });

  it('parseE2e_multiScan_returnsTwoScansWithOppositeLateralities', async () => {
    const file = loadFixture('multi-scan-OD-OS.e2e');
    const scans = await parseE2e(file);

    expect(scans).toHaveLength(2);

    // Both volumes share the same patientId + scanDate, distinct scanIndex.
    const [a, b] = scans as [E2eScan, E2eScan];
    expect(a.patientId).toBe('TEST-002');
    expect(b.patientId).toBe('TEST-002');
    expect(a.scanDate.toISOString().slice(0, 10)).toBe('2024-03-20');
    expect(b.scanDate.toISOString().slice(0, 10)).toBe('2024-03-20');
    expect(a.scanIndex).toBe(0);
    expect(b.scanIndex).toBe(1);

    const lateralities = scans.map((s) => s.laterality).sort();
    expect(lateralities).toEqual(['OD', 'OS']);
  });

  it('parseE2e_malformedHeader_throwsClearError', async () => {
    const garbage = new Uint8Array(100);
    // Fill with non-printable bytes so neither the multi-volume sentinel
    // NOR the plausible-magic check passes — the parser must surface a
    // clear error rather than silently returning an empty array.
    garbage.fill(0x01);
    const file = new File([garbage], 'garbage.e2e', {
      type: 'application/octet-stream',
    });
    await expect(parseE2e(file)).rejects.toThrow(/header magic/i);
  });

  it('parseE2e_emptyFile_throwsClearError', async () => {
    // Edge case: a 0-byte file should not crash with an arcane DataView
    // out-of-bounds — it should surface the same "too short" guard.
    const file = new File([new Uint8Array(0)], 'empty.e2e', {
      type: 'application/octet-stream',
    });
    await expect(parseE2e(file)).rejects.toThrow(/header magic|too short/i);
  });
});
