/*
 * LibreClinica is distributed under the
 * GNU Lesser General Public License (GNU LGPL).
 *
 * For details see: https://libreclinica.org/license
 * copyright (C) 2026 Department of Ophthalmology and Optometry,
 *                     Medical University of Vienna
 */
package at.ac.meduniwien.ophthalmology.libreclinica.config;

import liquibase.database.core.PostgresDatabase;

/**
 * Liquibase's PostgreSQL support, except that {@code autoIncrement} columns
 * stay {@code serial}.
 * <p>
 * Liquibase 3.6.3 created every {@code autoIncrement="true"} column as
 * {@code serial}: an owned sequence and a {@code DEFAULT nextval(...)}.
 * Liquibase 4 does that only below PostgreSQL 10 and otherwise emits
 * {@code GENERATED BY DEFAULT AS IDENTITY}, so a database built from scratch
 * by 4.x would differ from every existing one in 93 columns, and the
 * integration tests would run against a schema no production database has.
 * Keeping {@code serial} gives new databases the schema 3.6.3 built.
 * <p>
 * Registered in {@code META-INF/services/liquibase.database.Database}. The
 * higher priority makes Liquibase choose it over its own
 * {@link PostgresDatabase} for every PostgreSQL connection.
 */
public class SerialPostgresDatabase extends PostgresDatabase {

    @Override
    public int getPriority() {
        return PRIORITY_DATABASE;
    }

    @Override
    public boolean useSerialDatatypes() {
        return true;
    }
}
